# ===================================================================
# Examsy Microservices: Global Shared Configuration
# Inherited automatically by ALL microservices that connect to Config Server
# ===================================================================

# Eureka Service Discovery Registration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Spring Boot Actuator (Health & Metrics & Gateway Routes)
management.endpoints.web.exposure.include=health,info,metrics,prometheus,gateway
management.endpoint.health.show-details=always

# Shared Kafka Bootstrap Broker
spring.kafka.bootstrap-servers=localhost:9092
