server.port=8761
spring.application.name=examsy-eureka-server

# Standalone Eureka Server Configuration:
# Do not register Eureka Server with itself, and do not fetch registry from peers
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Eureka Server Tuning for Local Development:
# Disabling self-preservation ensures stopped microservices are quickly removed from the dashboard
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000

# Expose Actuator health endpoints
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
