name: Publish Microservices Docker Containers

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-images:
    name: Build & Push (${{ matrix.service }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - service: examsy-config-server
            port: 8888
          - service: examsy-eureka-server
            port: 8761
          - service: examsy-api-gateway
            port: 8080
          - service: examsy-auth-service
            port: 8081
          - service: examsy-profile-service
            port: 8082
          - service: examsy-class-service
            port: 8083
          - service: examsy-exam-service
            port: 8084
          - service: examsy-grading-service
            port: 8085
          - service: examsy-notification-service
            port: 8086
          - service: examsy-admin-service
            port: 8087

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: actions/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: actions/docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.service }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag
            type=sha,format=short

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./services/${{ matrix.service }}
          file: ./services/${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
